### ISSUE TITLE
反馈一些bug

### ISSUE THREAD

**Issue by Agnes4m** [btc-99/autotune_remix#1]
## 视频过短？
意思可能是，因为有一段midi是空的，导致视频不够凑数？（猜的）
```
MoviePy - Writing audio in raw_audioclip.wav
MoviePy - Done.
少女祈祷中...
100%|████████████████████████████████████████████████████████████████████████████████| 383/383 [01:35<00:00,  4.01it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.70it/s]
Moviepy - Building video F:\Program Files\mad\mang\autotune_remix\output_videos\track0.mp4.
MoviePy - Writing audio in track0TEMP_MPY_wvf_snd.mp3
chunk:   1%|▌                                                             | 42/4194 [00:00<00:18, 218.67it/s, now=None]Traceback (most recent call last):
  File "F:\Program Files\mad\mang\autotune_remix\launch.py", line 86, in <module>
    final_video.write_videofile(output_path + video_name)
  File "<decorator-gen-59>", line 2, in write_videofile
  File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-58>", line 2, in write_videofile
  File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-57>", line 2, in write_videofile
  File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "D:\python3.9.10\lib\site-packages\moviepy\video\VideoClip.py", line 293, in write_videofile
    self.audio.write_audiofile(audiofile, audio_fps,
  File "<decorator-gen-49>", line 2, in write_audiofile
  File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 206, in write_audiofile
    return ffmpeg_audiowrite(self, filename, fps, nbytes, buffersize,
  File "<decorator-gen-13>", line 2, in ffmpeg_audiowrite
  File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "D:\python3.9.10\lib\site-packages\moviepy\audio\io\ffmpeg_audiowriter.py", line 166, in ffmpeg_audiowrite
    for chunk in clip.iter_chunks(chunksize=buffersize,
  File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 85, in iter_chunks
    yield self.to_soundarray(tt, nbytes=nbytes, quantize=quantize,
  File "<decorator-gen-48>", line 2, in to_soundarray
  File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 127, in to_soundarray
    snd_array = self.get_frame(tt)
  File "<decorator-gen-15>", line 2, in get_frame
  File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 296, in make_frame
    sounds = [c.get_frame(t - c.start)*np.array([part]).T
  File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 296, in <listcomp>
    sounds = [c.get_frame(t - c.start)*np.array([part]).T
  File "<decorator-gen-15>", line 2, in get_frame
  File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 187, in <lambda>
    return self.fl(lambda gf, t: gf(t_func(t)), apply_to,
  File "<decorator-gen-15>", line 2, in get_frame
  File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "D:\python3.9.10\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 77, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "D:\python3.9.10\lib\site-packages\moviepy\audio\io\readers.py", line 170, in get_frame
    raise IOError("Error in file %s, "%(self.filename)+
OSError: Error in file audioclip.wav, Accessing time t=0.37-0.41 seconds, with clip duration=0 seconds,
```

## 音轨缺少？
不知道什么错误
```
Traceback (most recent call last):
  File "F:\Program Files\mad\mang\autotune_remix\launch.py", line 37, in <module>
    pitch0 = track[0][0][2]
IndexError: list index out of range
```

**Comment by btc-99** [comment]
是的，出现这个问题的原因是，你的视频文件小于midi中一个音符的长度，比如需要发音1s，而视频本身只有0.5s，所以会报错。解决办法就是找一个比较长的视频就行了。



---原始邮件---
发件人: "Agnes ***@***.***&gt;
发送时间: 2023年4月16日(周日) 晚上11:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [btc-99/autotune_remix] 反馈一些bug (Issue #1)




 
视频过短？
 
意思可能是，因为有一段midi是空的，导致视频不够凑数？（猜的）
 MoviePy - Writing audio in raw_audioclip.wav MoviePy - Done. 少女祈祷中... 100%|████████████████████████████████████████████████████████████████████████████████| 383/383 [01:35<00:00,  4.01it/s] 100%|████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.70it/s] Moviepy - Building video F:\Program Files\mad\mang\autotune_remix\output_videos\track0.mp4. MoviePy - Writing audio in track0TEMP_MPY_wvf_snd.mp3 chunk:   1%|▌                                                             | 42/4194 [00:00<00:18, 218.67it/s, now=None]Traceback (most recent call last):   File "F:\Program Files\mad\mang\autotune_remix\launch.py", line 86, in <module&gt;     final_video.write_videofile(output_path + video_name)   File "<decorator-gen-59&gt;", line 2, in write_videofile   File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration     return f(clip, *a, **k)   File "<decorator-gen-58&gt;", line 2, in write_videofile   File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default     return f(clip, *new_a, **new_kw)   File "<decorator-gen-57&gt;", line 2, in write_videofile   File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB     return f(clip, *a, **k)   File "D:\python3.9.10\lib\site-packages\moviepy\video\VideoClip.py", line 293, in write_videofile     self.audio.write_audiofile(audiofile, audio_fps,   File "<decorator-gen-49&gt;", line 2, in write_audiofile   File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration     return f(clip, *a, **k)   File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 206, in write_audiofile     return ffmpeg_audiowrite(self, filename, fps, nbytes, buffersize,   File "<decorator-gen-13&gt;", line 2, in ffmpeg_audiowrite   File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration     return f(clip, *a, **k)   File "D:\python3.9.10\lib\site-packages\moviepy\audio\io\ffmpeg_audiowriter.py", line 166, in ffmpeg_audiowrite     for chunk in clip.iter_chunks(chunksize=buffersize,   File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 85, in iter_chunks     yield self.to_soundarray(tt, nbytes=nbytes, quantize=quantize,   File "<decorator-gen-48&gt;", line 2, in to_soundarray   File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration     return f(clip, *a, **k)   File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 127, in to_soundarray     snd_array = self.get_frame(tt)   File "<decorator-gen-15&gt;", line 2, in get_frame   File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 89, in wrapper     return f(*new_a, **new_kw)   File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 93, in get_frame     return self.make_frame(t)   File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 296, in make_frame     sounds = [c.get_frame(t - c.start)*np.array([part]).T   File "D:\python3.9.10\lib\site-packages\moviepy\audio\AudioClip.py", line 296, in <listcomp&gt;     sounds = [c.get_frame(t - c.start)*np.array([part]).T   File "<decorator-gen-15&gt;", line 2, in get_frame   File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 89, in wrapper     return f(*new_a, **new_kw)   File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 93, in get_frame     return self.make_frame(t)   File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 136, in <lambda&gt;     newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))   File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 187, in <lambda&gt;     return self.fl(lambda gf, t: gf(t_func(t)), apply_to,   File "<decorator-gen-15&gt;", line 2, in get_frame   File "D:\python3.9.10\lib\site-packages\moviepy\decorators.py", line 89, in wrapper     return f(*new_a, **new_kw)   File "D:\python3.9.10\lib\site-packages\moviepy\Clip.py", line 93, in get_frame     return self.make_frame(t)   File "D:\python3.9.10\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 77, in <lambda&gt;     self.make_frame = lambda t: self.reader.get_frame(t)   File "D:\python3.9.10\lib\site-packages\moviepy\audio\io\readers.py", line 170, in get_frame     raise IOError("Error in file %s, "%(self.filename)+ OSError: Error in file audioclip.wav, Accessing time t=0.37-0.41 seconds, with clip duration=0 seconds,  
音轨缺少？
 
不知道什么错误
 Traceback (most recent call last):   File "F:\Program Files\mad\mang\autotune_remix\launch.py", line 37, in <module&gt;     pitch0 = track[0][0][2] IndexError: list index out of range
